# Generated by Django 3.2.5 on 2021-12-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='methylation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmg', models.CharField(max_length=20, verbose_name='biggest-beta-genes')),
                ('lrg', models.CharField(max_length=20, verbose_name='smallest-beta-genes')),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case')),
            ],
        ),
    ]
