# Generated by Django 3.2.5 on 2021-12-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='age',
            field=models.IntegerField(default='', null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='case',
            name='height',
            field=models.FloatField(default='', null=True, verbose_name='height_cm'),
        ),
        migrations.AlterField(
            model_name='case',
            name='weight',
            field=models.FloatField(default='', null=True, verbose_name='weight_kg'),
        ),
    ]
