# Generated by Django 3.2.5 on 2021-12-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20211219_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='age',
            field=models.IntegerField(null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='case',
            name='height',
            field=models.FloatField(null=True, verbose_name='height_cm'),
        ),
        migrations.AlterField(
            model_name='case',
            name='weight',
            field=models.FloatField(null=True, verbose_name='weight_kg'),
        ),
    ]
