# Generated by Django 3.2.5 on 2021-12-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='sd',
            new_name='cv',
        ),
    ]
